spring.application.name=spring-security-oauth2
server.port=8082

oauth.client.id=teksec-client
oauth.client.secret=teksec-secret
oauth.client.redirect-uri=http://127.0.0.1:8082/login/oauth2/code/teksec-client
oauth.client.access-token-validity=3600
oauth.client.refresh-token-validity=86400

